### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by MatthewZMD**
Hi, I am looking into some of your emacs configs and notice some interesting things that I find useful. However, I realize your emacs config doesn't have a license yet. Therefore I propose the GPLv3 license since it's the standard license for emacs projects.

### CODE REVIEW

**Comment by jborden** [comment]
Hi, I appreciate you reminding me of the need for a license. I should audit the rest of my code and make sure I have one in place. However, I prefer the MIT license for my work. I did add it to the dir, I am closing this pull request. Once again, thanks!f

**Comment by MatthewZMD** [comment]
Thank you, MIT is also fine. :)

**Comment by MatthewZMD** [comment]
@jborden Hi, just want to show you the "fork" I did to your javac-mode [java-one-click-run](https://github.com/MatthewZMD/java-one-click-run) What do you think? ;)

**Comment by jborden** [comment]
Glad you found the code useful... looks good!

**Pull request closed without merging**
